remote_theme: "jekyll/minima@1e8a445"
minima:
  nav_pages:
    - about.md
    - portfolio.md
  social_links:
    - title: Jekyll repository at GitHub
      icon: github
      url: "https://github.com/jekyll/jekyll"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/jekyllrb"
